### ISSUE TITLE
Style screens based on design

### ISSUE THREAD

**Issue by blurrah** [Team-Plofpigeon/vavio-application#13]
Style the screens based on the design. On hold because designs aren't done yet.

**Comment by mitchellslager** [comment]
Almost done with all the styling. Because I can not test video in the iOS emulator I can't work on that part. Might have to borrow someone's iPhone 6 for a few minutes tomorrow.

I also did work on the functionality of the app. Most things are working, except for:
- Uploading a video
- Making a new video
- Sharing the montage video
- Starting a new challenge

**Comment by blurrah** [comment]
Fixed in #35
